<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sean Telg">

<title>Week 6 - Conditioning – Econometrics I</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-787e033c7b6f65c9dfccb6078e5d2d34.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-a3f9cb8af720a2e54c76fd7b4321138d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-787e033c7b6f65c9dfccb6078e5d2d34.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

window.MathJax = {

  tex: {

    macros: {



      /* =========================

         Probability and statistics

         ========================= */



      E:   "\\operatorname{E}",

      Var: "\\operatorname{Var}",

      Cov: "\\operatorname{Cov}",

      Corr: "\\operatorname{Corr}",

      SD:  "\\operatorname{SD}",



      Pr: "\\operatorname{P}",



      /* =========================

         Asymptotics

         ========================= */



      plim: "\\operatorname{plim}",

      asy: "\\operatorname{asymptotic}",



      /* =========================

         Optimization

         ========================= */



      argmin: "\\operatorname*{arg\\,min}",

      argmax: "\\operatorname*{arg\\,max}",



      /* =========================

         Econometrics

         ========================= */



      OLS: "\\operatorname{OLS}",

      MLE: "\\operatorname{MLE}",

      BLUE: "\\operatorname{BLUE}",



      /* =========================

         Distributions

         ========================= */



      N: "\\mathcal{N}",



      /* =========================

         Common notation

         ========================= */



      iid: "\\overset{\\mathrm{iid}}{\\sim}",

      ind: "\\perp\\!\\!\\!\\perp",



      /* =========================

         Vectors and matrices

         ========================= */



      R: "\\mathbb{R}",

      Rn: "\\mathbb{R}^n",

      Rp: "\\mathbb{R}^p",



      /* =========================

         Estimators

         ========================= */



      betaHat: "\\hat{\\beta}",

      thetaHat: "\\hat{\\theta}",



      /* =========================

         Derivatives

         ========================= */



      d: "\\mathrm{d}",



      /* =========================

         Miscellaneous

         ========================= */



      diag: "\\operatorname{diag}",

      tr: "\\operatorname{tr}",

      rank: "\\operatorname{rank}"

    }

  }

};

</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../part 1/index.html">Part 1</a></li><li class="breadcrumb-item"><a href="../part 1/week6.html">Week 6</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Econometrics I</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Why this online book?</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course information</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../econometrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Before we start…</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 1</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Short introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/exercises-week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/exercises-week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/exercises-week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/exercises-week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/exercises-week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/week6.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Week 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 1/exercises-week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 6</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part 2/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/exercises-week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/exercises-week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/exercises-week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/exercises-week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/exercises-week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part 2/exercises-week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises Week 6</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#this-weeks-contents" id="toc-this-weeks-contents" class="nav-link active" data-scroll-target="#this-weeks-contents">This week’s contents</a></li>
  <li><a href="#the-simple-linear-regression-model" id="toc-the-simple-linear-regression-model" class="nav-link" data-scroll-target="#the-simple-linear-regression-model">The simple linear regression model</a>
  <ul class="collapse">
  <li><a href="#unbiasedness-of-the-least-squares-estimator" id="toc-unbiasedness-of-the-least-squares-estimator" class="nav-link" data-scroll-target="#unbiasedness-of-the-least-squares-estimator">Unbiasedness of the least-squares estimator</a></li>
  </ul></li>
  <li><a href="#empirical-applications" id="toc-empirical-applications" class="nav-link" data-scroll-target="#empirical-applications">Empirical applications</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../part 1/index.html">Part 1</a></li><li class="breadcrumb-item"><a href="../part 1/week6.html">Week 6</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Week 6 - Conditioning</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p><a href="https://research.vu.nl/en/persons/sean-telg/">Sean Telg</a> </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>📚 This week’s roadmap
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Chapter 6.</li>
</ul>
</div>
</div>
<section id="this-weeks-contents" class="level2">
<h2 class="anchored" data-anchor-id="this-weeks-contents">This week’s contents</h2>
<p>So far, we covered Chapter 1 to 3 in ITE. We derived the estimators <span class="math inline">\(\widehat{\beta} = (X'X)^{-1}X'y\)</span>, <span class="math inline">\(s^{2} = e'e/(n-k)\)</span> under the condition that they are unbiased. We continued by deriving test statistics for single and multiple linear restrictions. These results were found based on the classical assumptions for the linear regression model, except for one. The assumption that <span class="math inline">\(X\)</span> is nonrandom has been motivated in Section 2.7 using the argument that the basics of econometric theory do not change if we make this simplifying assumption. Whereas this is true, any good econometrician needs to know how to deal with <strong>conditioning</strong>, which is the title of this week’s Chapter 6. Since you are already familiar with this topic from your previous probability theory and statistics course, we will focus almost exclusively on the linear regression model. We revisit some of the previously found results and see how their derivation changes when <span class="math inline">\(X\)</span> is assumed random.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>📚 Read in ITE
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Section 6.1 - 6.4. These sections intuitively explain the concept of conditioning and help you refresh your memory on the concept.</li>
<li>Section 6.5. This section introduces two very important concepts: the <strong>law of total expectation</strong> (also called the <em>law of iterated expectations</em> or the <em>tower property</em>) and the <strong>law of total variance</strong>.</li>
</ul>
</div>
</div>
</section>
<section id="the-simple-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="the-simple-linear-regression-model">The simple linear regression model</h2>
<p>Consider the simple linear regression model <span class="math display">\[
y_{i} = \beta_{1} + \beta_{2}x_{i} + u_{i}, \qquad (i = 1,\ldots, n),
\]</span> where <span class="math inline">\(x_{i}\)</span> is assumed to be random. This means that <span class="math inline">\(u_{i}\)</span> is no longer the only random part on the right-hand side of this equation and thus we need to make an assumption about the relationship between <span class="math inline">\(u_{i}\)</span> and <span class="math inline">\(x_{i}\)</span>.</p>
<p>An often chosen assumption is <strong>mean-independence</strong>, which can be expressed as <span class="math inline">\(E(u_{i}|x_{i}) = 0\)</span>, because it is stronger than uncorrelatedness between <span class="math inline">\(u_{i}\)</span> and <span class="math inline">\(x_{i}\)</span> and weaker than independence (which is deemed unrealistic). This condition is also called <strong>strict exogeneity</strong>. In addition, <strong>variance-independence</strong> is imposed, which shows that the variance of <span class="math inline">\(u_{i}\)</span> does not depend on <span class="math inline">\(x_{i}\)</span>, i.e.&nbsp;<span class="math inline">\(\Var(u_{i}|x_{i}) = \sigma^{2}\)</span>. This is called <strong>homoskedasticity</strong> and we study its implications in more detail in the second part of this course.</p>
<p>These assumptions give a clear interpretation to the linear regression. Note that <span class="math display">\[
\begin{aligned}
E(y_{i}|x_{i}) &amp;= E(\beta_{1} + \beta_{2}x_{i} + u_{i} | x_{i}) \\
               &amp;= \beta_{1} + \beta_{2}E(x_{i}|x_{i}) + E(u_{i} | x_{i}) \\
               &amp;= \beta_{1} + \beta_{2}x_{i},
\end{aligned}
\]</span> because <span class="math inline">\(E(u_{i}|x_{i}) = 0\)</span> by strict exogeneity. Thus, the <strong>population linear regression line</strong> simply represents the conditional mean of <span class="math inline">\(y_{i}\)</span> given <span class="math inline">\(x_{i}\)</span>. This also reveals how to proceed in terms of prediction. In that case, we need the <strong>sample linear regression line</strong> which then represents an estimate of the conditional mean of <span class="math inline">\(y_{i}\)</span> given <span class="math inline">\(x_{i}\)</span>.</p>
<p>We may also compute the conditional variance of <span class="math inline">\(y_{i}\)</span> given <span class="math inline">\(x_{i}\)</span>. Note that <span class="math display">\[
\Var(y_{i} | x_{i}) = \Var(\beta_{1} + \beta_{2}x_{i} + u_{i} | x_{i}) = \Var(u_{i}|x_{i}) = \sigma^{2},
\]</span> since the systemic part <span class="math inline">\(\beta_{1} + \beta_{2}x_{i}\)</span> is fixed conditional on <span class="math inline">\(x_{i}\)</span>. The difference with the unconditional variance of <span class="math inline">\(y_{i}\)</span> is important to notice. Using the law of total variance: <span class="math display">\[
\begin{aligned}
E(y_{i}) &amp;= E(\Var(y_{i}|x_{i})) + \Var(E(y_{i}|x_{i})) \\
         &amp;= E(\sigma^{2}) + \Var(\beta_{1} + \beta_{2}x_{i}) \\
         &amp;= \sigma^{2} + \beta_{2}^{2}\Var(x_{i}) \\
         &amp;= \sigma^{2} + \beta_{2}^{2}\sigma^{2}_{x},
\end{aligned}
\]</span> which has the nice interpretation that the total variation in <span class="math inline">\(y_{i}\)</span> is the sum of variation explained by <span class="math inline">\(x_{i}\)</span> and the unexplained variation from <span class="math inline">\(u_{i}\)</span>. So, even though the variance of <span class="math inline">\(y_{i}\)</span> conditional on <span class="math inline">\(x_{i}\)</span> is always <span class="math inline">\(\sigma^{2}\)</span>, the unconditional variance also contains variation arising because <span class="math inline">\(x_{i}\)</span> itself varies across observations.</p>
<section id="unbiasedness-of-the-least-squares-estimator" class="level3">
<h3 class="anchored" data-anchor-id="unbiasedness-of-the-least-squares-estimator">Unbiasedness of the least-squares estimator</h3>
<p>Because <span class="math inline">\(x_{i}\)</span> is now <strong>random</strong>, the least-squares estimators <span class="math inline">\(\widehat{\beta}_{1}\)</span>, <span class="math inline">\(\widehat{\beta}_{2}\)</span> and <span class="math inline">\(s^{2} = \frac{1}{n-2}\sum_{i=1}^{n} \widehat{u}_{i}^{2}\)</span> are now highly nonlinear functions of <span class="math inline">\((y, X)\)</span>. Under the conditions that we just imposed, we can still show unbiasedness of these estimators. Let’s focus on <span class="math inline">\(\widehat{\beta}_{2}\)</span>.</p>
<p>Under correct specification, i.e.&nbsp;the model and DGP coincide,note that we can write <span class="math display">\[
\widehat{\beta}_{2} = \beta_{2} + \frac{\sum_{i=1}^{n} (x_{i} - \overline{x})u_{i}}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}},
\]</span> which we already showed in Week 2.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Reminder">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Reminder
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Note that <span class="math display">\[
\begin{aligned}
\widehat{\beta}_{1\2} &amp;= \frac{\sum_{i=1}^{n} (x_{i} - \overline{x})(y_{i} - \overline{y})}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}} \\
&amp;= \frac{\sum_{i=1}^{n} (x_{i} - \overline{x})(\beta_{1} + \beta_{2}x_{i} + u_{i} - (\beta_{1} + \beta_{2}\overline{x} + \overline{u}))}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}} \\
&amp;= \frac{\sum_{i=1}^{n} (x_{i} - \overline{x})(\beta_{2}(x_{i} - \overline{x}) + (u_{i} - \overline{u}))}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}} \\
&amp;= \beta_{2} + \frac{\sum_{i=1}^{n} (x_{i} - \overline{x})(u_{i} - \overline{u})}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}} \\
&amp;= \beta_{2} + \frac{\sum_{i=1}^{n} (x_{i} - \overline{x})u_{i}}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}}.
\end{aligned}
\]</span> Note that we plugged in the DGP at the second equality, the third and fourth equalities are rearranging terms, and the last equality follows from <span class="math inline">\(\overline{u}\sum_{i=1}^{n}(x_{i} - \overline{x}) = 0\)</span>.</p>
</div>
</div>
</div>
<p>Taking expectations now yields <span class="math display">\[
\begin{aligned}
E(\widehat{\beta}_{2}) &amp;= E\left[ \beta_{2} + \frac{\sum_{i=1}^{n}(x_{i} - \overline{x})u_{i}}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}} \right] \\
&amp;= E(\beta_{2}) + E \left[ \frac{\sum_{i=1}^{n}(x_{i} - \overline{x})u_{i}}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}}  \right] \\
&amp;= \beta_{2} + E \left[ \frac{\sum_{i=1}^{n}(x_{i} - \overline{x})u_{i}}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}}  \right].
\end{aligned}
\]</span> To obtain the desired result <span class="math inline">\(E(\widehat{\beta}_{2}) = \beta_{2}\)</span>, we need to show that this second term equals zero. We are going to use the <em>law of total expectations</em>, because the term involves several random variables. If we define <span class="math inline">\(X = (x_{1}, \ldots, x_{n})\)</span>, we can proceed as follows: <span class="math display">\[
\begin{aligned}
E \left( \frac{\sum_{i=1}^{n}(x_{i} - \overline{x})u_{i}}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}}  \right) &amp;=
E_{X} \left( \frac{\sum_{i=1}^{n}(x_{i} - \overline{x})E_{u_{i}|X}(u_{i}| X)}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}}  \right) \\
&amp;= E_{X} \left( \frac{\sum_{i=1}^{n}(x_{i} - \overline{x}) \cdot 0}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}}  \right)
= 0,
\end{aligned}
\]</span> where some subtle steps need extra explanation:</p>
<ul>
<li>The first equality makes use of the law of total expectations. We have to condition on <span class="math inline">\(X = (x_{1}, \ldots, x_{n})\)</span> and not just a single <span class="math inline">\(x_{i}\)</span>, otherwise we may not take <span class="math inline">\(\sum_{i=1}^{n} (x_{i} - \overline{x})\)</span> outside of the inner expectation.</li>
<li>The inner expectation is taken with respect to the conditional distribution <span class="math inline">\(u_{i} | x_{1}, \ldots, x_{n}\)</span>, while the outer expectation is with respect to <span class="math inline">\(x_{1}, \ldots, x_{n}\)</span>. To emphasize with respect to what distribution we take the expectation, we included them as subscripts. <em>You may do this as well, but note that it is not mandatory.</em></li>
<li>By combining <span class="math inline">\(\Cov(u_{i}, u_{j}) = 0\)</span> for all <span class="math inline">\(i \neq j\)</span> and normality, we have independence of all pairs of observations <span class="math inline">\((x_{i}, y_{i})\)</span> and <span class="math inline">\((x_{j}, y_{j})\)</span> for all <span class="math inline">\(i \neq j\)</span>. Therefore, we can conclude <span class="math inline">\(E_{u_{i}|X}(u_{i} | X) = E_{u_{i}|X}(u_{i} | x_{1}, \ldots, x_{n}) = E_{u_{i}|x_{i}}(u_{i} | x_{i}) = 0\)</span>.</li>
</ul>
<p>We have now calculated the unconditional expectation of <span class="math inline">\(\widehat{\beta}_{2}\)</span>, which shows that the estimator is indeed unbiased. For completeness, we can also compute its variance. Let us first compute the conditional variance: <span class="math display">\[
\begin{aligned}
\Var(\widehat{\beta}_{2} | X) &amp;= \Var\left( \beta_{2} + \frac{\sum_{i=1}^{n}(x_{i} - \overline{x})u_{i}}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}} \Bigg| X \right) \\
&amp;= \frac{1}{[\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}]^{2}} \Var\left(\sum_{i=1}^{n}(x_{i} - \overline{x})u_{i} | X \right) \\
&amp;= \frac{\sum_{i=1}^{n}(x_{i} - \overline{x})^{2}}{[\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}]^{2}} \Var(u_{i} | X ) \\
&amp;= \frac{\sigma^{2}}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}}.
\end{aligned}
\]</span> We are now ready to compute the unconditional variance using the law of total variance.: <span class="math display">\[
\begin{aligned}
\Var(\widehat{\beta}_{2}) &amp;= E(\Var(\widehat{\beta}_{2} | X)) + \Var(E(\widehat{\beta}_{2}|X)) \\
&amp;= E\left( \frac{\sigma^{2}}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}} \right) + \Var(\beta_{2}) \\
&amp;= \sigma^{2} E\left(\frac{1}{\sum_{i=1}^{n} (x_{i} - \overline{x})^{2}} \right).
\end{aligned}
\]</span></p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>📚 Read in ITE
</div>
</div>
<div class="callout-body-container callout-body">
<p>You are now ready to read how this generalizes to the multiple linear regression model.</p>
<ul>
<li>Section 6.6 - 6.8.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="empirical-applications" class="level2">
<h2 class="anchored" data-anchor-id="empirical-applications">Empirical applications</h2>
<p>The past weeks’ main focus has been on the theory behind the multiple linear regression model. We have looked at the ideal conditions, derived estimators and their corresponding standard errors as well as confidence intervals, prediction (intervals) and studied how to perform tests for single and multiple linear restrictions on the vector <span class="math inline">\(\beta\)</span>. We have even touched upon the topics model selection and model averaging.</p>
<p>This puts us in a position to apply the model to real data and to correctly interpret its results. Running these analyses yourself will be addressed in the second part of the course, but let us consider two empirical applications from the book <em>Mastering Econometrics</em>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="The relationship between price and sales">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The relationship between price and sales
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A shop specializing in shoes has sold <span class="math inline">\(n = 420\)</span> pairs of shoes in one week. The shop sells shoes in many price categories, and for each sale we know the price. The shopkeeper wants to understand the relationship between price (<span class="math inline">\(x\)</span>) and sales (<span class="math inline">\(y\)</span>). Estimating the linear regression model <span class="math display">\[
y_{i} = \beta_{1} + \beta_{2} x_{i} + u_{i}
\qquad
(i=1,\dots,n),
\]</span> she obtains the following results:</p>
<div id="tbl-regression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Regression results
</figcaption>
<div aria-describedby="tbl-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Coefficient</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. error</th>
<th style="text-align: right;"><span class="math inline">\(t\)</span>-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;"><span class="math inline">\(24.394\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.664\)</span></td>
<td style="text-align: right;"><span class="math inline">\(36.730\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Price</td>
<td style="text-align: right;"><span class="math inline">\(-0.066\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.006\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-11.750\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>graphically represented as <img src="images/week5-salesprices.png" class="img-fluid" style="width:100.0%" alt="The data and the estimated regression line."></p>
<ol type="a">
<li>Discuss the relationship between the variables in light of the estimation result. Is the relationship as expected?</li>
<li>Obtain a <span class="math inline">\(95\%\)</span> confidence interval for <span class="math inline">\(\beta_{2}\)</span>.</li>
<li>Obtain a prediction for the number of sales given a price of 80. And also for a price of 300. Are these predictions reliable?</li>
<li>Describe a limitation of the linear model in describing the relationship. Is the linear model useful for this data set?</li>
</ol>
<p>We could answer these questions as follows:</p>
<ol type="a">
<li><p>The regression line suggests a negative relationship between price and sales. There are about 21 sales at a price of 50 euros, about 18 at a price of 100 euros, and about 15 at a price of 150 euros. Formally, a unit increase in price leads to a decrease of about 0.066 in sales. The relationship is statistically significant at the conventional <span class="math inline">\(5\%\)</span> and <span class="math inline">\(1\%\)</span> significance levels <span class="math inline">\(\alpha\)</span>, which can be verified by comparing the <span class="math inline">\(t\)</span>-statistic with the <span class="math inline">\((\alpha/2)\)</span>-quantiles (for two-sided tests) of the Student <span class="math inline">\(t\)</span>-distribution with 418 degrees of freedom. In practice, we use the normal approximation when the degrees of freedom exceeds <span class="math inline">\(30\)</span>. Since we know that <span class="math inline">\(\Pr(|z|&lt;1.96)=0.95\)</span> and <span class="math inline">\(\Pr(|z|&lt;2.57)=0.99\)</span> when <span class="math inline">\(z \sim N(0,1)\)</span>, and both <span class="math inline">\(36.730\)</span> and <span class="math inline">\(11.750\)</span> are well above 1.96 and 2.57, the two estimates are significant.</p></li>
<li><p>The <span class="math inline">\(95\%\)</span> confidence interval is given by <span class="math display">\[
(\hat\beta_{2} - 1.96\sqrt{s^{2}v_{22}},\; \hat\beta_{2} + 1.96\sqrt{s^{2}v_{22}})
= (-0.078, -0.054),
\]</span> where the standard error <span class="math inline">\(\sqrt{s^{2}v_{22}}\)</span> equals <span class="math inline">\(0.006\)</span>. Thus, <span class="math inline">\(\beta_{2} = 0\)</span> is not included in the <span class="math inline">\(95\%\)</span> confidence interval, in agreement with the significance of the estimate discussed under (a).</p></li>
<li><p>For a price <span class="math inline">\(x_{*} = 80\)</span>, the prediction is <span class="math inline">\(\hat{y}_{*} = \hat{\beta}_{1} + \hat{\beta}_{2} \times 80 = 19.114\)</span>, and for <span class="math inline">\(x_{*} = 300\)</span>, the prediction is <span class="math inline">\(19.114\)</span>. The second prediction is less reliable because we have only a few observations for such large prices.</p></li>
<li><p>One of the limitations of a linear approximation is that it may not be a good approximation when we move away from the center. For example, sales cannot be negative, and a linear model would lead to negative sales whenever the price is (very) large. This does not mean that the model is useless, but it only provides a useful approximation for prices between, say, 30 and 200.</p></li>
</ol>
</div>
</div>
</div>
<p>The previous empirical application makes use of the simple linear regression model, which is very popular due to its straightforward interpretation and ability to clearly visualize the results. However, a regression model with only one independent variable is often insufficient to capture the essence of the problem. If we regress sales on price, then we explicitly allow sales to only depend on that single factor. It is very likely that sales are also explained by other factors than price, such as the type of shoes, the material of the shoes, the friendliness of the salesperson, et cetera. These variables are currently absorbed in the error term, and they may be correlated with price. Because of this, we may systematically over- or underestimate <span class="math inline">\(\beta_{2}\)</span>. This argument is made clearly in Section 3.8 of ITE: we might include other regressors (auxiliary variables) simply to get a reliable estimate of the coefficient related to our focus variable (i.e., price in this case). We now consider an empirical application making use of the multiple linear regression model.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Returns to scale in electricity supply">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Returns to scale in electricity supply
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>(If you want to run the analysis yourself, you can download the data set ME-data-3-01.xlsx from <a href="https://sites.google.com/view/seantelg/mastering-econometrics">my website</a>. These are real data that are obtained from <em>Nerlove, M. (1963), Returns to scale in electricity supply, Ch. 7 in: Christ, C. et al.&nbsp;(Eds.), Measurement in Economics, Stanford University Press, pp.&nbsp;167–198.</em>).</p>
<p>The file contains data on 145 electric utility companies in 1955. There are five columns corresponding to total costs in millions of dollars (TC), output in billions of kilowatt hours (<span class="math inline">\(Q\)</span>), price of labor (<span class="math inline">\(p_L\)</span>), price of capital (<span class="math inline">\(p_K\)</span>) and price of fuels (<span class="math inline">\(p_F\)</span>). Estimate model <span class="math inline">\(y = X\beta + u\)</span>, where <span class="math inline">\(y = \log \text{TC}\)</span> and <span class="math display">\[
X = \left(\imath : \log Q : \log p_L : \log p_K : \log p_F\right).
\]</span></p>
<ol type="a">
<li>Report the parameter estimates and standard errors.</li>
<li>Perform a <span class="math inline">\(t\)</span>-test on all coefficients to verify which ones are significantly different from zero at the <span class="math inline">\(5\%\)</span> significance level.</li>
<li>Test and interpret the hypothesis <span class="math inline">\(\beta_{2} = \beta_{3} = \beta_{4} = \beta_5 =0\)</span>.</li>
<li>Test and interpret the hypothesis <span class="math inline">\(\beta_{2} = \beta_{4} = 0\)</span>.</li>
</ol>
<p>(The file ME-code-3-04.R, available on the same website page mentioned above, can be used for the analysis.)</p>
<ol type="a">
<li>We obtain the following estimation results:</li>
</ol>
<div id="tbl-regression" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Estimated regression results
</figcaption>
<div aria-describedby="tbl-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Coefficient</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. error</th>
<th style="text-align: right;"><span class="math inline">\(t\)</span>-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;"><span class="math inline">\(-3.527\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.774\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-1.987\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\log Q\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.720\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.017\)</span></td>
<td style="text-align: right;"><span class="math inline">\(41.244\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\log p_L\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.436\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.291\)</span></td>
<td style="text-align: right;"><span class="math inline">\(1.499\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\log p_F\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.427\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.100\)</span></td>
<td style="text-align: right;"><span class="math inline">\(4.249\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\log p_K\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-0.220\)</span></td>
<td style="text-align: right;"><span class="math inline">\(0.339\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-0.648\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<ol start="2" type="a">
<li><p>The column <span class="math inline">\(t\)</span>-value gives the desired information. If we test two-sidedly and use the normal approximation, then we simply ask whether the absolute <span class="math inline">\(t\)</span>-values are larger or smaller than 1.96. This is the case for <span class="math inline">\(\log Q\)</span> and <span class="math inline">\(\log p_F\)</span>, and also (but marginally) for the constant term. Hence, the coefficients of <span class="math inline">\(\log Q\)</span> and <span class="math inline">\(\log p_F\)</span> are significantly different from zero, the intercept is marginally significant, and the coefficients of <span class="math inline">\(\log p_L\)</span> and <span class="math inline">\(\log p_K\)</span> are not significantly different from zero.</p></li>
<li><p>The null hypothesis states that all coefficients, except for the intercept, are equal to zero. This test is sometimes called the <em>test of overall significance</em>, and it tests whether the <em>intercept-only model</em> fits the data as well as our proposed regression model. In our case, the value of the <span class="math inline">\(F\)</span>-statistic is 14.585, which is higher than the critical value of the <span class="math inline">\(F(4,140)\)</span>-distribution, which is 2.436. Thus, we reject the null hypothesis. Our set of four regressors thus has some bearing on the explanation of total cost.</p></li>
<li><p>We now test whether the coefficients of <span class="math inline">\(\log Q\)</span> and <span class="math inline">\(\log p_F\)</span> are jointly equal to zero. This test is sometimes called the <em>partial <span class="math inline">\(F\)</span>-test</em>. The value of the <span class="math inline">\(F\)</span>-statistic is now 14.585, which is larger than 3.061, the critical value of the <span class="math inline">\(F(2,140)\)</span>-distribution. Thus, we reject the null hypothesis. Keeping these two regressors in the model is therefore a good idea.</p></li>
</ol>
</div>
</div>
</div>
<p>These two empirical applications only highlight how we can use the results that we derived over the past weeks. We will consider different applications in more detail during the second part of the course. We then develop misspecification tests, such that we cannot just estimate models and assess their fit, but also test whether they fulfill the assumptions (ideal conditions.)</p>


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-copyright"><h2 class="anchored quarto-appendix-heading">Copyright</h2><div class="quarto-appendix-contents"><div>Sean Telg, 2026. All Rights Reserved</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>